added enum and barell
DimaUstim/pets_project pull request #10
Opened 2022-10-07 13:52 UTC by DimaUstim

2022-10-10 10:27 UTC, AndriiPanasenkoSolvve reviewed
Code style issues

2022-10-10 12:43 UTC, AndriiPanasenkoSolvve approved these changes

2022-10-10 12:50 UTC, AndriiPanasenkoSolvve requested changes
Please avoid using API URL in every service

2022-10-11 07:35 UTC, AndriiPanasenkoSolvve approved these changes

2022-10-11 16:55 UTC, Maksym-Antsybor approved these changes

2022-10-11 16:55 UTC, merged